apiVersion: v1
entries:
  netobserv-operator:
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.11.0-community
    created: "2026-02-09T11:43:25.565431493+01:00"
    dependencies:
    - condition: install.prom
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: ~28.2.0
    - condition: install.prom-stack
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: ~80.4.1
    - condition: install.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: ~2.10.3
    description: Network Observability in Kubernetes based on eBPF.
    digest: d70472b1a9d8ff645c88accdc73130e334360851e1d51ee47c3786209c8a96b6
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - netobserv
    - ebpf
    - ipfix
    - flow tracing
    - netflows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: lberetta@redhat.com
      name: Leandro Beretta
    - email: ljira@redhat.com
      name: Luis Jira
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.11.0.tgz
    version: 1.11.0
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.10.1-community
    created: "2026-01-19T17:43:30.741838014+01:00"
    dependencies:
    - condition: install.prom
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: ~28.2.0
    - condition: install.prom-stack
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: ~80.4.1
    - condition: install.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: ~2.10.3
    description: Network Observability in Kubernetes based on eBPF.
    digest: ff5827d4e2ecf88d59c095e3e18f7c4855fa8f56d074875034892640df774e38
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - netobserv
    - ebpf
    - ipfix
    - flow tracing
    - netflows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: lberetta@redhat.com
      name: Leandro Beretta
    - email: ljira@redhat.com
      name: Luis Jira
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.10.1.tgz
    version: 1.10.1
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.10.0-community
    created: "2025-11-04T17:39:59.04667514+01:00"
    dependencies:
    - condition: install.prom
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: ~27.23.0
    - condition: install.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: ~2.10.2
    description: Network Observability in Kubernetes based on eBPF.
    digest: aa374894577eec7499db5203bf061dc1ac29f2d399bd43fa9908ed48914ac73e
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: lberetta@redhat.com
      name: Leandro Beretta
    - email: ljira@redhat.com
      name: Luis Jira
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.10.0.tgz
    version: 1.10.0
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.9.2-community
    created: "2025-09-08T11:10:57.824389531+02:00"
    dependencies:
    - condition: install.prom
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: ~27.23.0
    - condition: install.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: ~2.10.2
    description: Network Observability in Kubernetes based on eBPF.
    digest: 0b3aea8db4f37399f8575659cd9eb7eaafad2dd14ffa99fac822066bf78631ac
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: lberetta@redhat.com
      name: Leandro Beretta
    - email: ljira@redhat.com
      name: Luis Jira
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.9.2.tgz
    version: 1.9.2
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.9.1-community
    created: "2025-07-09T09:54:04.728912194+02:00"
    dependencies:
    - condition: install.prom
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: ~27.7.1
    - condition: install.loki
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: ~2.10.2
    description: Network Observability in Kubernetes based on eBPF.
    digest: 59fd520c8586d982977121b83ed494b0460a99721c5f72e4d39cd1831d25d08a
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.9.1.tgz
    version: 1.9.1
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.9.0-community
    created: "2025-07-03T09:16:00.849641893+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 40e5e66c1fac850c5ecd5744389af6c72e027fb54e90adeee91da45ac5fd6175
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.9.0.tgz
    version: 1.9.0
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.8.2-community
    created: "2025-07-03T09:16:00.847373242+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 026b51667d244f1c445d7fb0d5a09ab770b3de59700c3461675890f284b3deb7
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.2.tgz
    version: 1.8.2
  - apiVersion: v2
    appVersion: 1.8.1-community
    created: "2025-07-03T09:16:00.843697559+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: fa047dcad6940e9f4c73d014280b9a10713d1e3f9ab5ebb973c79f98a559d6c4
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.1.tgz
    version: 1.8.1
  - apiVersion: v2
    appVersion: 1.8.0-community
    created: "2025-07-03T09:16:00.840592816+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 95a50e7776c6fa5d5ff5d2986a5d83700e29e73dcdd04d7fc4c0d5c70a604192
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.0.tgz
    version: 1.8.0
generated: "2026-02-09T11:43:25.503996928+01:00"
