apiVersion: v1
entries:
  netobserv-operator:
  - annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Deep Insights
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
    apiVersion: v2
    appVersion: 1.9.0-community
    created: "2025-07-03T09:16:00.849641893+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 40e5e66c1fac850c5ecd5744389af6c72e027fb54e90adeee91da45ac5fd6175
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 1.8.2-community
    created: "2025-07-03T09:16:00.847373242+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 026b51667d244f1c445d7fb0d5a09ab770b3de59700c3461675890f284b3deb7
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.2.tgz
    version: 1.8.2
    annotations:
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: "Deep Insights"
      artifacthub.io/screenshots: |
        - title: Topology view
          url: https://netobserv.io/static/assets/images/about/topology-main.png
        - title: Flow details
          url: https://netobserv.io/static/assets/images/about/network-traffic-main.png
  - apiVersion: v2
    appVersion: 1.8.1-community
    created: "2025-07-03T09:16:00.843697559+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: fa047dcad6940e9f4c73d014280b9a10713d1e3f9ab5ebb973c79f98a559d6c4
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.1.tgz
    version: 1.8.1
  - apiVersion: v2
    appVersion: 1.8.0-community
    created: "2025-07-03T09:16:00.840592816+02:00"
    description: Network Observability in Kubernetes based on eBPF.
    digest: 95a50e7776c6fa5d5ff5d2986a5d83700e29e73dcdd04d7fc4c0d5c70a604192
    home: https://netobserv.io/
    icon: https://netobserv.io/static/assets/images/netobserv.svg
    keywords:
    - network observability
    - ebpf
    - ipfix
    - flow tracing
    - flows
    - topology
    - network
    - observability
    maintainers:
    - email: jpinsonn@redhat.com
      name: Julien Pinsonneau
    - email: jtakvori@redhat.com
      name: Joel Takvorian
    - email: mmahmoud@redhat.com
      name: Mohamed S. Mahmoud
    - email: ocazade@redhat.com
      name: Olivier Cazade
    - email: stlee@redhat.com
      name: Steven Lee
    name: netobserv-operator
    sources:
    - https://github.com/netobserv/network-observability-operator
    - https://github.com/netobserv/flowlogs-pipeline
    - https://github.com/netobserv/netobserv-ebpf-agent
    - https://github.com/netobserv/network-observability-console-plugin
    - https://github.com/netobserv/network-observability-cli
    type: application
    urls:
    - https://netobserv.io/static/helm/netobserv-operator-1.8.0.tgz
    version: 1.8.0
generated: "2025-07-03T09:16:00.83609754+02:00"
